USE universidad;
/*1 UNIV*/SELECT apellido1, apellido2, nombre FROM persona WHERE tipo = "alumno" ORDER BY apellido1, apellido2, nombre;
/*2*/SELECT nombre, apellido1, apellido2 FROM persona WHERE telefono IS NULL AND tipo = "alumno";
/*3*/SELECT nombre FROM persona WHERE LEFT(fecha_nacimiento, 4) = "1999" AND tipo = "alumno";
/*4*/SELECT nombre FROM persona WHERE RIGHT(nif, 1) = "K" AND telefono IS NULL AND tipo = "profesor";
/*5*/SELECT nombre FROM asignatura WHERE curso = 3 AND cuatrimestre = 1 AND id_grado = 7;
/*6*/SELECT per.apellido1, per.apellido2, per.nombre, dep.nombre FROM persona as per JOIN profesor as pro ON pro.id_profesor = per.id JOIN departamento as dep ON pro.id_departamento = dep.id ORDER BY per.apellido1, per.apellido2, per.nombre;
/*7*/SELECT asi.nombre, ce.anyo_inicio, ce.anyo_fin from alumno_se_matricula_asignatura as ama JOIN persona as per ON per.id = ama.id_alumno JOIN asignatura as asi ON ama.id_asignatura = asi.id JOIN curso_escolar as ce ON ama.id_curso_escolar = ce.id WHERE per.nif = "26902806M";
/*8*/SELECT DISTINCT dep.nombre FROM departamento as dep JOIN profesor as pro ON dep.id = pro.id_departamento JOIN asignatura as asi ON asi.id_profesor = pro.id_profesor JOIN grado as gra ON gra.id = asi.id_grado WHERE gra.nombre = 'Grado en Ingeniería Informática (Plan 2015)';
/*9*/SELECT DISTINCT per.nombre FROM alumno_se_matricula_asignatura as ama JOIN curso_escolar as ce ON ama.id_curso_escolar = ce.id JOIN persona as per ON per.id = ama.id_alumno WHERE per.tipo = "alumno" AND ce.anyo_inicio = "2018";
/*1 LJ RJ*/SELECT dep.nombre, per.apellido1, per.apellido2, per.nombre FROM persona as per LEFT JOIN profesor as pro ON pro.id_profesor = per.id LEFT JOIN departamento as dep ON dep.id = pro.id_departamento WHERE dep.nombre IS NOT NULL ORDER BY dep.nombre, per.apellido1, per.apellido2, per.nombre;
/*2*/SELECT per.nombre FROM departamento as dep LEFT JOIN profesor as pro ON dep.id = pro.id_departamento LEFT JOIN persona as per ON pro.id_profesor = per.id WHERE pro.id_departamento IS NULL AND per.nombre IS NOT NULL;
/*3*/SELECT dep.nombre FROM departamento dep LEFT JOIN profesor as pro ON dep.id = pro.id_departamento WHERE id_departamento IS NULL;
/*4*/SELECT per.nombre FROM asignatura as asi RIGHT JOIN profesor as pro ON asi.id_profesor = pro.id_profesor LEFT JOIN persona as per ON pro.id_profesor = per.id WHERE asi.nombre IS NULL AND per.nombre IS NOT NULL;
/*5*/SELECT asi.nombre FROM asignatura as asi LEFT JOIN profesor as pro ON asi.id_profesor = pro.id_profesor WHERE asi.id_profesor IS NULL;
/*6*/SELECT dep.nombre FROM departamento dep LEFT JOIN profesor as pro ON dep.id = pro.id_departamento LEFT JOIN asignatura as asi ON asi.id_profesor = pro.id_profesor LEFT JOIN alumno_se_matricula_asignatura as ama ON ama.id_asignatura = asi.id GROUP BY dep.nombre HAVING MAX(ama.id_curso_escolar) IS NULL; 
/*1 RESUM*/SELECT COUNT(*) FROM persona WHERE tipo = "alumno";
/*2*/SELECT COUNT(*) FROM persona where tipo = "alumno" AND LEFT(fecha_nacimiento, 4) = "1999";
/*3*/SELECT dep.nombre, COUNT(pro.id_profesor) as num_prof FROM persona as per JOIN profesor as pro ON per.id = pro.id_profesor JOIN departamento as dep ON dep.id = pro.id_departamento GROUP BY dep.nombre ORDER BY num_prof DESC;
/*4*/SELECT dep.nombre, COUNT(pro.id_profesor) as num_prof FROM departamento as dep LEFT JOIN profesor as pro ON dep.id = pro.id_departamento GROUP BY dep.nombre;
/*5*/SELECT gra.nombre, COUNT(asi.id) num_asig FROM grado as gra LEFT JOIN asignatura as asi ON gra.id = asi.id_grado GROUP BY gra.nombre ORDER BY num_asig DESC;
/*6*/SELECT gra.nombre, COUNT(asi.id) num_asig FROM grado as gra JOIN asignatura as asi ON gra.id = asi.id_grado GROUP BY gra.nombre HAVING num_asig > 40 ORDER BY num_asig DESC;
/*7*/SELECT gra.nombre, asi.tipo, SUM(asi.creditos) as sum_creditos FROM grado as gra JOIN asignatura as asi ON gra.id = asi.id_grado GROUP BY gra.nombre, asi.tipo;
/*8*/SELECT ce.anyo_inicio, COUNT(id_alumno) as num_alumn FROM asignatura as asi JOIN alumno_se_matricula_asignatura as ama ON asi.id = ama.id_asignatura JOIN curso_escolar as ce ON ama.id_curso_escolar = ce.id GROUP BY ce.anyo_inicio;
/*9*/SELECT per.id, per.nombre, per.apellido1, per.apellido2, COUNT(asi.id) num_asig FROM persona as per LEFT JOIN profesor as pro ON per.id = pro.id_profesor LEFT JOIN asignatura as asi ON pro.id_profesor = asi.id_profesor GROUP BY per.id, per.nombre, per.apellido1, per.apellido2 ORDER BY num_asig DESC;
/*10*/SELECT * FROM persona WHERE fecha_nacimiento = (SELECT MAX(fecha_nacimiento) FROM persona);
/*11*/SELECT per.nombre FROM persona as per JOIN profesor as pro ON per.id = pro.id_profesor JOIN departamento as dep ON pro.id_departamento = dep.id LEFT JOIN asignatura as asi ON asi.id_profesor = pro.id_profesor WHERE asi.id IS NULL;